#!/usr/bin/env node

/**
 * Post-install script to fix Prisma 7 client module resolution
 * Creates the default.js file and compiles TypeScript to JavaScript
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const prismaClientPath = path.join(__dirname, '..', 'node_modules', '.prisma', 'client');
const defaultJsPath = path.join(prismaClientPath, 'default.js');
const clientTsPath = path.join(prismaClientPath, 'client.ts');
const clientJsPath = path.join(prismaClientPath, 'client.js');

if (fs.existsSync(clientTsPath)) {
  // Compile TypeScript files to JavaScript
  try {
    execSync(
      `npx tsc ${prismaClientPath}/*.ts ${prismaClientPath}/internal/*.ts --outDir ${prismaClientPath} --module commonjs --target es2020 --esModuleInterop --skipLibCheck --moduleResolution node --allowSyntheticDefaultImports`,
      { stdio: 'pipe', cwd: path.join(__dirname, '..') }
    );
    console.log('✅ Compiled Prisma client TypeScript files');
  } catch (error) {
    console.log('⚠️  TypeScript compilation had issues');
  }
  
  // Create default.js that uses compiled JavaScript
  const defaultJsContent = `// Auto-generated by postinstall script
// Use compiled JavaScript file
module.exports = require('./client.js');
`;

  fs.writeFileSync(defaultJsPath, defaultJsContent);
  console.log('✅ Created .prisma/client/default.js');
  
  // Patch @prisma/client/default.js for Turbopack compatibility
  const atPrismaClientDefaultPath = path.join(__dirname, '..', 'node_modules', '@prisma', 'client', 'default.js');
  if (fs.existsSync(atPrismaClientDefaultPath)) {
    const patchedContent = `// Patched for Turbopack compatibility
// Use static relative path that Turbopack can resolve at build time
// From node_modules/@prisma/client to node_modules/.prisma/client
module.exports = require('../../.prisma/client/default.js');
`;
    fs.writeFileSync(atPrismaClientDefaultPath, patchedContent);
    console.log('✅ Patched @prisma/client/default.js for Turbopack');
  }
  
  // Create symlink for @prisma/client path resolution
  const atPrismaPath = path.join(__dirname, '..', 'node_modules', '@prisma');
  const atPrismaDotPrismaPath = path.join(atPrismaPath, '.prisma');
  if (!fs.existsSync(atPrismaDotPrismaPath)) {
    fs.mkdirSync(atPrismaPath, { recursive: true });
    try {
      fs.symlinkSync('../../.prisma', atPrismaDotPrismaPath, 'dir');
      console.log('✅ Created symlink for @prisma/.prisma');
    } catch (e) {
      // Symlink might already exist
    }
  }
} else {
  console.log('⚠️  Prisma client not found, run: npm run db:generate');
}
